### ISSUE TITLE
Supreme Commander 2

### ISSUE THREAD

**Issue by plottingCreeper** [MASGAU/MASGAU#106] opened 2014-02-26 02:00 UTC
There seems to be a problem with detecting the saves for Supreme Commander 2, here is the exception information;

The folder Supreme Commander 2  could not be found in C:\Users\plottingCreeper\AppData\Local\Gas Powered Games

   at MASGAU.Location.Holders.DetectedLocationPathHolder..ctor(EnvironmentVariable ev, String absolute_root, String path, String owner) in E:\GIT\MASGAU\MASGAU.Common\Location\Holders\DetectedLocationPathHolder.cs:line 44
   at MASGAU.Location.EvFolder.createDetectedLocations(LocationPath loc, String owner) in E:\GIT\MASGAU\MASGAU.Common\Location\EvFolder.cs:line 71
   at MASGAU.Location.ALocationHandler.getPaths(LocationPath get_me) in E:\GIT\MASGAU\MASGAU.Common\Location\ALocationHandler.cs:line 87
   at MASGAU.Location.ASystemLocationHandler.getPaths(LocationPath get_me) in E:\GIT\MASGAU\MASGAU.Common\Location\ASystemLocationHandler.cs:line 90
   at MASGAU.Location.SystemLocationHandler.getPaths(LocationPath get_me) in E:\GIT\MASGAU\MASGAU.Windows\Location\SystemLocationHandler.cs:line 400
   at MASGAU.Location.ALocationHandler.getPaths(ALocation get_me) in E:\GIT\MASGAU\MASGAU.Common\Location\ALocationHandler.cs:line 66
   at MASGAU.Location.ALocationsHandler.getPaths(ALocation get_me) in E:\GIT\MASGAU\MASGAU.Common\Location\ALocationsHandler.cs:line 113
   at MASGAU.GameEntry.Detect() in E:\GIT\MASGAU\MASGAU.Common\Game\GameEntry.cs:line 293
   at MASGAU.Games.detectGames(List`1 these_games) in E:\GIT\MASGAU\MASGAU.Common\Game\Games.cs:line 303
   at MASGAU.Games.detectGames() in E:\GIT\MASGAU\MASGAU.Common\Game\Games.cs:line 239
   at MASGAU.Main.MainProgramHandler.detectGames() in E:\GIT\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 44
   at MASGAU.Main.MainProgramHandler.doWork(Object sender, DoWorkEventArgs e) in E:\GIT\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 39
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

It also has the same issue if 
C:\Users\plottingCreeper\Documents\My Games\Gas Powered Games\Supreme Commander 2\
and
C:\Users\plottingCreeper\Documents\My Games\Square Enix\Supreme Commander 2\
exist.

Every time I click the send report button, it says send failed.
If I click close, the whole program closes. If reopened, it does the same thing.

Side note, the exact same thing happens on my friends computer.
I use Windows 7, he uses windows 8.1

![masgau](https://f.cloud.github.com/assets/6550725/2265847/a7618910-9e89-11e3-9034-e3944baecd83.jpg)

**Comment by sanmadjack** [comment] 2014-02-26 13:51
Fascinating, I'll look into this

**Comment by sanmadjack** [comment] 2014-02-26 14:26
I found the issue. The game's data definitions have a space at the end of the path:

``` xml
  <game name="SupremeCommander2" follows="SupremeCommander" added="1955-11-05T00:00:00" updated="2012-08-27T18:13:36">
    <title>Supreme Commander 2</title>
    <version os="Windows">
      <locations>
        <path ev="userdocuments" path="Mis juegos\SquareEnix\Supreme Commander 2"/>
        <path ev="userdocuments" path="My Games\Gas Powered Games\Supreme Commander 2 "/>
        <path ev="userdocuments" path="My Games\SquareEnix\Supreme Commander 2 "/>
      </locations>
      <files>
        <include path="savegames"/>
      </files>
      <files type="Replays">
        <include path="replays"/>
      </files>
      <contributor>GameSave.Info</contributor>
    </version>
    <version os="Windows" type="Settings">
      <locations>
        <path ev="localappdata" path="Gas Powered Games\Supreme Commander 2 "/>
      </locations>
      <files>
        <include filename="Game.prefs"/>
      </files>
      <contributor>simtech76</contributor>
    </version>
  </game>
```

Windows ignores this space when MASGAU does its quick "hey Windows, does this exist?" check, but when it does its own manual check, it's not there. MASGAU throws this exception because, theoretically, there should never be different answers to those two questions. Correcting the data should be easy enough, but I'm going to add some additional code so that future versions will be able to compensate for this. If you want to be able to take care of this quickly on your own, just edit c:\programdata\masgau\s.xml to remove the spaces in the definition that matches what I pasted above.

**Comment by sanmadjack** [comment] 2014-02-26 14:31
As a note, since you can't even start up MASGAU at this point, you won't be able to update your data via the auto-update. You'll either need to manually edit your s.xml file, or wait until I have a new build ready that will fix this for you. Let me know what you'd like to do.

**Comment by plottingCreeper** [comment] 2014-02-26 14:44
I renamed the folder, and wrote a preloader script for SC2 to change the name back before it starts, and rename it again once it closes. I have a sort of fix for it, but I am looking forwards to a build where this isn't needed.

**Comment by sanmadjack** [comment] 2014-02-26 19:56
Well, fix no more. I updated the game data to not have the spaces, so if you can start MASGAU you can hit the update button and download the latest data. I've already tested and confirmed that Supreme Commander 2 will detect properly with it. An updated build that will cope with this kind of discrepancy is coming, but I need to work out some kinks first.

**Comment by sanmadjack** [comment] 2014-02-26 22:52
Or you can try this new, barely-tested build!

https://drive.google.com/file/d/0By2Mfv6zO9SkQmVLWnJGTU90amc/edit?usp=sharing

**Comment by plottingCreeper** [comment] 2014-02-27 03:52
New and barely tested? Count me in!

**Comment by plottingCreeper** [comment] 2014-02-27 03:53
Installed and run, works perfectly so far.

**Comment by sanmadjack** [comment] 2014-02-27 14:15
Awesome! Care to poke around it, see if you can ferret out any bugs? Maybe just click every button and see what happens? I'm going to close this issue now, if you run into anything else just make another one :D

**Closed as completed by sanmadjack** 2014-02-27 14:15 UTC
Labels: Bug

**Comment by plottingCreeper** [comment] 2014-02-28 02:41
Clicked every button, working fine. 
Did the same on my friends computer, using the same build, working fine.

**Comment by sanmadjack** [comment] 2014-02-28 19:32
That's awesome, thanks!
